name: Trigger Repository Dispatch
on:
  workflow_dispatch:

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: az_quickstart_release
          client-payload: '{"version": "2.11.1"}'
